services:
  cryptalk.api:
    image: ${DOCKER_REGISTRY-}cryptalkapi
    container_name: cryptalk.api
    environment:
      - ConnectionStrings__DatabaseConnection=Host=${POSTGRES_HOST};Port=${POSTGRES_PORT};Database=${POSTGRES_DB};Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD}
    build:
      context: .
      dockerfile: Cryptalk/Dockerfile
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"

  cryptalk.database:
    image: postgres:latest
    container_name: cryptalk.database
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ./.containers/cryptalk-db:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}

  cryptalk.migration:
    build:
      context: .
      dockerfile: Cryptalk/Dockerfile
      target: final-migration
    depends_on:
      - cryptalk.database
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    command: ./migrate.sh
    restart: "no"